### ISSUE TITLE
Transfer crate? 

### ISSUE THREAD

**Issue by seanmonstar** [ghmlee/rust-request#7]
Hey Graham. I've tried sending emails to you, not sure if you've seen them. I noticed it's been a while since you've updated this crate, and I was wondering if you expect to continue doing so. If not, I have plans for a client crate wrapping hyper. I'm also the author of hyper :D 

Would you be amenable to transferring me the name, if you don't have plans for it?

**Comment by ghmlee** [comment]
Sorry I can not transfer the repo. I plan to build the next version of rust-request.

**Comment by robinst** [comment]
Doesn't look like that happened. @ghmlee would you reconsider? reqwest now has a lot of users judging by the number of downloads, see here: https://crates.io/crates/reqwest

It would be nice for new Rust users to get a nice up-to-date client with "request" as the crate name instead of the current "reqwest" which looks like a typo and is hard to type.

**Comment by jhpratt** [comment]
@ghmlee There hasn't been even a single commit in nearly four years. Your comment from two years ago indicates plans to build a new version; this obviously never happened. What would it take for you to allow the transfer to occur? Your crate has ~6200 downloads, compared to reqwest's ~880,000. It's by no means comparable.

**Comment by aloucks** [comment]
@ghmlee Another year has passed and there have been no new commits to `request`. Would you, at this time, reconsider transferring the crate?

**Comment by luojia65** [comment]
@ghmlee Yes another year have passed
